apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_CHAT_MODEL
              value: "llama3.2:latest"
            - name: OLLAMA_CHAT_URL
              value: "http://ollama-chat:11434"
            - name: OLLAMA_EMBEDDING_MODEL
              value: "nomic-embed-text"
            - name: OLLAMA_EMBEDDING_URL
              value: "http://ollama-embeddings:11434"
          volumeMounts:
            - name: pdfs
              mountPath: /data/pdf
            - name: chroma-data
              mountPath: /data/chroma
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
      volumes:
        - name: pdfs
          hostPath:
            path: /embeddings/data/pdf
            type: DirectoryOrCreate
        - name: chroma-data
          hostPath:
            path: /embeddings/data/chroma
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
