apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  labels:
    app: streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      containers:
        - name: streamlit-ui
          image: streamlit-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui
spec:
  selector:
    app: streamlit-ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
